<?php

/* MYUSERS VERSION */
$version = '0.01';
include("db-info.php"); //This file has all database information autogenerated into.

GLOBAL $errors;
GLOBAL $successes;




$errors = array();
$successes = array();

/* Create a new mysqli object with database connection parameters */
$mysqli = new mysqli($db_host, $db_user, $db_pass, $db_name);
GLOBAL $mysqli;

/* GET PAGE URL */
function PageURL() {
 $pageURL = 'http';
 if (array_key_exists('HTTPS', $_SERVER) && $_SERVER["HTTPS"] == "on") {$pageURL .= "s";}
 $pageURL .= "://";
 if ($_SERVER["SERVER_PORT"] != "80") {
  $pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].$_SERVER["REQUEST_URI"];
 } else {
  $pageURL .= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];
 }
 return $pageURL;
}
/* END GET PAGE URL - PULL REQUEST BY SKYLETER */

if(mysqli_connect_errno()) {
	echo "<center><br><br><br>";
	echo "Connection Failed: - Error " . mysqli_connect_errno();
	echo "<br>Is MyUsers configured correctly? <br><b>If you haven't installed MyUsers, <a href='install/'>click here</a></b> <br><h5><font color='red'>Remember to DELETE the install folder after installing. </font></h5>";
    echo "<hr> MyUsers version ".$version." - Running on: "; 
	echo PageURL();
	echo "</center>";
	exit();
}

//Direct to install directory, if it exists
if(is_dir("install/"))
{
	header("Location: install/");
	die();

}

?>
